# Build stage
FROM node:18-alpine AS build
ENV NODE_ENV=production

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Serve the production build with a lightweight server
RUN npm install -g serve
CMD ["serve", "-s", "build"]
