services:
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.5
    ports:
      - "${THREDDS_PORT}:${THREDDS_PORT}"
    volumes:
      - ${THREDDS_PUBLIC_DIR}:${THREDDS_PUBLIC_DIR_DOCKER} # For .nc files
      - ${THREDDS_WEB_XML}:${THREDDS_WEB_XML_DOCKER}  # CORS config
      - ${THREDDS_CATALOG_XML}:${THREDDS_CATALOG_XML_DOCKER}  # Catalog config
      - ${THREDDS_CONFIG_XML}:${THREDDS_CONFIG_XML_DOCKER}  # Palette and styles
      - ${THREDDS_WMS_CONFIG_XML}:${THREDDS_WMS_CONFIG_XML_DOCKER}  # Palette and styles
    networks:
      - thredds_network

  backend:
    container_name: backend
    build:
      context: ${BACKEND_CONTEXT}
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV_DEV}
    networks:
      - thredds_network

  frontend:
    container_name: frontend
    build:
      context: ${FRONTEND_CONTEXT_DEV}
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV_DEV}
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL_DEV}
      - REACT_APP_THREDDS_URL=${REACT_APP_THREDDS_URL_DEV}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public/locales:/app/public/locales # translation files
    networks:
      - thredds_network

networks:
  thredds_network:
