services:
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.5
    ports:
      - 8080:8080
    volumes:
      - /var/thredds/public:/usr/local/tomcat/content/thredds/public # For .nc files
      - /var/thredds/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml  # CORS config
      - /var/thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml  # Catalog config
      - /var/thredds/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml  # Palette and styles
      - /var/thredds/wmsConfig.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml  # Palette and styles
    restart: always
    networks:
      - thredds_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - thredds_network

  nginx-frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
      args:
        REACT_APP_API_BASE_URL: "/api"
        REACT_APP_THREDDS_URL: "/thredds"
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/public/locales:/app/public/locales # translation files
      - /etc/nginx/certs:/etc/nginx/certs
    networks:
      - thredds_network
    restart: always

networks:
  thredds_network: