version: '3.8'

services:
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.5
    ports:
      - "8080:8080"
    volumes:
      - ./thredds/public:/usr/local/tomcat/content/thredds/public # For .nc files
      - ./thredds/web.xml:/usr/local/tomcat/webapps/thredds/WEB-INF/web.xml  # CORS config
      - ./thredds/catalog.xml:/usr/local/tomcat/content/thredds/catalog.xml  # Catalog config
      - ./thredds/threddsConfig.xml:/usr/local/tomcat/content/thredds/threddsConfig.xml  # Palette and styles
      - ./thredds/wmsConfig.xml:/usr/local/tomcat/content/thredds/wmsConfig.xml  # Palette and styles
    networks:
      - thredds_network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - thredds_network
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"  # Expose port 80 from the NGINX container to port 3000
    environment:
      - NODE_ENV=production
      - REACT_APP_API_BASE_URL=/3001  # Relative URL for production
      - REACT_APP_THREDDS_URL=/8080/thredds  # Relative URL for production
    networks:
      - thredds_network
      
networks:
  thredds_network: