services:
  thredds:
    container_name: thredds
    image: unidata/thredds-docker:5.5
    ports:
      - "${THREDDS_PORT}:${THREDDS_PORT}"
    volumes:
      - ${THREDDS_PUBLIC_DIR}:${THREDDS_PUBLIC_DIR_DOCKER} # For .nc files
      - ${THREDDS_WEB_XML}:${THREDDS_WEB_XML_DOCKER}  # CORS config
      - ${THREDDS_CATALOG_XML}:${THREDDS_CATALOG_XML_DOCKER}  # Catalog config
      - ${THREDDS_CONFIG_XML}:${THREDDS_CONFIG_XML_DOCKER}  # Palette and styles
      - ${THREDDS_WMS_CONFIG_XML}:${THREDDS_WMS_CONFIG_XML_DOCKER}  # Palette and styles
    restart: always
    networks:
      - thredds_network

  backend:
    container_name: backend
    build:
      context: ${BACKEND_CONTEXT}
      dockerfile: Dockerfile.prod
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV_PROD}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - thredds_network

  nginx-frontend:
    container_name: frontend
    build:
      context: ${FRONTEND_CONTEXT_PROD}
      dockerfile: ${FRONTEND_DOCKERFILE_PROD}
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL_PROD}
        REACT_APP_THREDDS_URL: ${REACT_APP_THREDDS_URL_PROD}
    ports:
      - 80:80
      - 443:443
    environment:
      - NODE_ENV=${NODE_ENV_PROD}
    volumes:
      - ./frontend/public/locales:/app/public/locales # translation files
      - ${NGINX_CERTS_DIR}:${NGINX_CERTS_DIR}
    networks:
      - thredds_network
    restart: unless-stopped

networks:
  thredds_network:

volumes:
  backend_node_modules:
