# Build stage
FROM node:14-alpine AS build
ENV NODE_ENV=production
WORKDIR /app

# Copy package.json and package-lock.json and install dependencies
COPY package*.json ./
RUN npm ci --production || npm install --production

# Copy the rest of the application code
COPY . .

# Production Stage: Use a smaller base image
FROM node:14-alpine

WORKDIR /app

# Copy the built application
COPY --from=build /app /app

EXPOSE 3001

CMD ["node", "index.js"]
