# Use a base image with Node.js for development
FROM node:14-alpine AS development

# Set environment variable
ENV NODE_ENV=development

# Install nodemon globally for development
RUN npm install -g nodemon

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies from package.json
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose port 3001 for the Node.js backend
EXPOSE 3001

# Run nodemon for hot-reloading during development
CMD ["nodemon", "index.js"]
